### ISSUE TITLE
Only works if calling zappa update from linux

### ISSUE THREAD

**Issue by dhcracchiolo** [nonbeing/mysqlclient-python3-aws-lambda#4]
Awesome layer by the way!  I'm using Zappa to deploy.  Works like a charm if I update my lambda function from linux however if I try to update it from macos I still get:

NameError: name '_mysql' is not defined

Any ideas?

I'm using python 3.8.10
mysql 8.0.27

**Comment by nonbeing** [comment]
Hi there - thanks, I hope you find the layer useful. I haven't used Zappa for deployment, only "Serverless Framework".

```
NameError: name '_mysql' is not defined
```

This is happening because you're not including the layer properly in your Lambda function? If you're using one of the pre-built layer zips, you should not face this issue regardless of where you deploy from. Unless Zappa is trying to bundle your OS's `libmysqlclient.so` file instead of using the one built-into the layer zip. Please ensure that your Lambda function is referring to the proper layer created properly as per the instructions in the project README.

**Comment by dhcracchiolo** [comment]
Oh my god!  You're a genius!  It works!  For anyone else who has this problem, here's my zappa_settings.json:

```

"dev": {
        "app_function": "server.app",
        "profile_name": "default",
        "project_name": "<>",
        "runtime": "python3.8",
        "s3_bucket": "<>",
        "aws_region": "us-east-1",
        "certificate_arn": "<>",
        "domain": "<>",
        "timeout_seconds": 15,
        "layers": ["arn:aws:lambda:us-east-1:165014769753:layer:mysqlclient:1",
        "arn:aws:lambda:us-east-1:165014769753:layer:ffmpeg:1"],
        "exclude": ["boto3*",
      "botocore*",
      "mysqlclient*",
      "MySQLdb*",
      "_mysql*",
        "mysqlclient"
        ]
    },

```

Thank you so much dude!  You're worth your weight in gold!

**Comment by nonbeing** [comment]
Glad I could help 👍
